# Om rapporten {#om}

## Forfattere

**Sveinung Arnesen** er Forsker I ved NORCE, og førsteamanuensis II ved Institutt for administrasjons- og organisasjonsvitenskap, UiB. 
PhD-graden ble avlagt ved Institutt for sammenliknende politikk, UiB. 
Arnesen er Norges nasjonale koordinator for European Social Survey, og leder for tiden to relevante forskningsprosjekter som begge er finansiert av Norges forskningsråd: 1.Demokratisk innovasjon i praksis: Forskning på medvirkning og legitimitet i kommunale beslutningsprosesser, og 2. Can Fair Decision-Making Procedures Increase the Legitimacy of Democracies? (avsluttes februar 2021). 

**Mikael P. Johannesson** er forsker ved NORCE, og PhD-kandidat ved Institutt for sammenliknende politikk, UiB.
Han har bred erfaring med eksperimentelle metoder, maskinlæring (inkludert deep learning), og surveyforskning.
Johannesson har utviklerkompetanse i statistikkprogrammet R, samt erfaring med Python (inkludert TensorFlow og Keras). 

## Referansegruppe 

**Anne Lise Fimreite** er professor ved Institutt for administrasjon og organisasjonsvitenskap, UiB.
Hun har tidligere ledet den forskningsrådsfinansierte evaluering av NAV-reformen og har arbeidet mye med styringsutfordringer i flernivåsystem. 
Hun har også nylig vært medlem av det offentlige utvalget som i 2019 leverte forslag til ny forvaltningslov (NOU 2019:5) og har egen erfaring fra offentlig forvaltning som prorektor ved UiB i fire år fra 2013 til 2017. 

**Jacob Aars** er professor ved Institutt for administrasjons- og organisasjonsvitenskap, UiB, og har ledet den NFR-finansierte evalueringen av NAV-reformen (tok over da Fimreite gikk inn i rektoratet ved UiB). 
Han har blant annet forsket på lokaldemokrati og tilfredshet med offentlige tjenester.

## Data

Datagrunnlaget for denne rapporten er samlet inn i Norsk medborgerpanels runde 22 og 23.
Norsk medborgerpanel er en internettbasert undersøkelse om nordmenns holdninger til viktige samfunnstema.
Panelet drives av samfunnsforskere ved Universitetet i Bergen og NORCE, og er et non-profit prosjekt utelukkende benyttet til forskningsformål. 
Deltakerne representerer et tverrsnitt av den norske befolkningen, som noen ganger i året inviteres til å si sin mening i viktige spørsmål om norsk samfunn og politikk.

Panelet blir driftet av [Digital samfunnsvitenskapelig kjernefasilitet (DIGSSCORE)](www.digsscore.uib.no).

Samlet antall respondenter som svarte på deler av denne undersøkelsen var 3971.
Typisk antall respondenter for hvert spørsmål er om lag 2000.

Mer informasjon om datagrunnlaget presenteres i rapportens vedlegg XX. 
Data er åpent tilgjengelig for forskere, og kan lastes ned ved å kontakte [Sikt – Kunnskapssektorens tjenesteleverandør (tidligere kjent som NSD)](https://sikt.no/).
[Metoderapport for data kan lastes ned her.](https://www.uib.no/en/digsscore/122162/methodology-and-field-periods)

## Finansiering
Forskningsrapporten er finansiert av [NAV Forskning og Utvikling](https://www.nav.no/no/nav-og-samfunn/kunnskap/fou-midler/pagaende-fou-prosjekter2/navs-tiltak-og-virkemidler).
Finansieringen er bidragsfinansiert, det vil si uten krav til motytelse. 
